### ISSUE TITLE
No support for array of links

### ISSUE THREAD

**Issue by jasoncarr0** [marcuslange/akka-http-hal#5]
The HAL spec (as in https://tools.ietf.org/html/draft-kelly-json-hal-08#section-4.1.1) offers support for an array of links, for instance:

```
{
  "_links": {
    "self": {
      ...
    },
    "author": [{
      "title": "Jane Doe",
      "href": "/authors/1"
    },{
      "title": "John Smith",
      "href": "/authors/2"
    }]
  }
}
```

Does not appear to be constructible with this API.

Proposed fix: abstract Link to a trait. Then implement with SingleLink(href, templated, ...) and ArrayLink(SingleLink*)

Unfortunately, I can't see a fix without breaking backwards compatibility in some way.

Perhaps withArrayLinks: Option[Map[String, Seq[Link]]] would be the best way of moving forward

**Comment by marcuslange** [comment]
Good catch. I’ll review and try to get an update pushed in the next couple of days.

**Comment by marcuslange** [comment]
Sorry for the delay. This capability has been added and documentation updated with example. Backwards compatibility was maintained.

**Comment by jasoncarr0** [comment]
Thanks, and it's no big deal. I've been too busy to want to work on the project that I had wanted this for anyway.
